name: Trigger auto deployment for ca-sample-nodejs-self-dev-002

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-sample-nodejs-self-dev-002-AutoDeployTrigger-51ebdf95-764e-4c8f-8706-8365e0a19582.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CASAMPLENODEJSSELFDEV002_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CASAMPLENODEJSSELFDEV002_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CASAMPLENODEJSSELFDEV002_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ca2b2e2edd56acr.azurecr.io
          registryUsername: ${{ secrets.CASAMPLENODEJSSELFDEV002_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CASAMPLENODEJSSELFDEV002_REGISTRY_PASSWORD }}
          containerAppName: ca-sample-nodejs-self-dev-002
          resourceGroup: rg-self-dev-002
          imageToBuild: ca2b2e2edd56acr.azurecr.io/ca-sample-nodejs-self-dev-002:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


